### ISSUE TITLE
Tube block seems have some alias in new version

### ISSUE THREAD

**Issue by Snownee** [oMilkyy/SimpleTubes#11]
![2017-07-22_21 31 18](https://user-images.githubusercontent.com/16059084/28491582-2d2d6962-6f27-11e7-9622-97af32b0c191.png)

**Comment by oMilkyy** [comment]
I can't seem to recreate this in my dev environment, any ideas on how to recreate this, I believe that I have fixed it in the next version already.

**Comment by Snownee** [comment]
Fixed
