### ISSUE TITLE
Items cannot drop in chest in the middle using this structure

### ISSUE THREAD

**Issue by Snownee** [oMilkyy/SimpleTubes#12]
![2017-07-22_21.37.16.png](https://ooo.0o0.ooo/2017/07/22/597358314f213.png)

**Comment by oMilkyy** [comment]
Fixed this issue, going to build a new release now, thanks for your help testing the mod, it's extremely helpful

**Comment by Snownee** [comment]
This issue has been fixed in the new version, but seems that items cannot update route after I place a container near tubes.
