### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Darkosto** [oMilkyy/SimpleTubes#7]
Hello, 

looks like there's a crash when hooking up Simple Tubes between chests:

https://pastebin.com/PzCnLFGF

MC: 1.11.2
Simple Tubes: 0.0.2
Forge: 2414

Thank you :)
Darkosto

**Comment by oMilkyy** [comment]
That's not caused by SimpleTubes, an error occured at 

> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@51a8313b from coremod TANLoadingPlugin

One of the mods you have uses a coremod that's conflicting with SimpleTubes, I don't use coremod so it's not down to me to fix

Please contact the author of said coremod.

Thanks, oMilkyy

**Comment by Darkosto** [comment]
Thanks.
